const discotecaCadis = [
    {"data" : "Albinoni, Tommaso (1671–1750) – Concierto para trompeta en Si bemol mayor, Op. 7 nº 3. Intérpretes: Maurice André (trompeta) y English Chamber Orchestra. Director: Sir Charles Mackerras."},
    {"data" : "Albinoni, Tommaso (1671–1750) – Concierto para trompeta en Si bemol mayor, Op. 7 nº 6. Intérpretes: Maurice André (trompeta) y English Chamber Orchestra. Director: Sir Charles Mackerras."},
    {"data" : "Albinoni, Tommaso (1671–1750) – Concierto para cinco instrumentos en Si bemol mayor, Op.5 n° 1. Intérpretes: Los Solistas de Zagreb. Director: Antonio Janigro."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Cantata para el tiempo de Epifanía, BWV 200. Intérpretes: Conjunto coral y sinfónico de Stuttgart. Director: Marcel Couraud."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Concierto de Brandenburgo nº 3, primer movimiento. Orquesta Sinfónica de la Radio de Berlín. Director: Albert von Camus."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Concierto de Brandenburgo nº 1 en Fa mayor BWV 1046. Intérpretes: Orquesta Filarmónica de Berlín. Director: Herbert von Karajan. "},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Concierto de Brandenburgo nº 2 en Fa mayor BWV 1047. Intérpretes: Orquesta Filarmónica de Berlín. Director: Herbert von Karajan. "},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Concierto de Brandenburgo nº 3 en Sol mayor BWV 1048. Intérpretes: Orquesta Filarmónica de Berlín. Director: Herbert von Karajan. "},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Concierto de Brandenburgo nº 4 en Sol mayor BWV 1067. Intérpretes: Orquesta Filarmónica de Berlín. Director: Herbert von Karajan. "},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Concierto de Brandenburgo nº 5 en Re mayor BWV 1050. Intérpretes: Orquesta Filarmónica de Berlín. Director: Herbert von Karajan. "},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Concierto de Brandenburgo nº 6 en Si bemol mayor BWV 1051. Intérpretes: Orquesta Filarmónica de Berlín. Director: Herbert von Karajan. "},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Fuga para laúd, BWV 1000. Intérprete: John Williams (guitarra)."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Misa en Si menor. Intérpretes: Nicolai Geda, Elisabeth Schwarzkopff, Marga Höffgen, Heinz Reffus; Coro y Orquesta de la Sociedad Amigos de la Música de Viena, Director: Herbert von Karajan."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Misa en Si menor. Intérpretes: Gundula Janowitz (soprano), Christa Ludwig (contralto), Peter Schreier (tenor), Robert Kerns (barítono) y Karl Riedderbusch (bajo). Coro y Orquesta Filarmónica de Berlín. Director: Herbet von Karajan. "},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Oratorio de Navidad. Intérpretes: Erich Majkut, Elisabeth Roon, Dagmar Hermann-Braun, Walter Berry, Laurence Dutoit; Coro de Cámara de la Academia y Orquesta Sinfónica de Viena, Director: Ferdinand Grossmann."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Oratorio de Navidad. Intérpretes: Gunduka Janowitz, Christa Ludwig, Fritz Wunderlich, Franz Crass; Coro Bach de Munich y Orquesta Bach de Munich. Director: Karl Richter."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Oratorio de Pascua, BWV 249. Intérpretes: Conjunto coral y sinfónico de Stuttgart. Director: Marcel Couraud."},
    {"data" : "Bach, Johann Sebastian (1685–1750) –  Pasión según San Mateo, BWV 244. Intérpretes: Ernst Häfliger, Walter Berry, Agnes Giebel, Marga Höffgen, John van Kesteren, Franz Crass, Leo Ketelaars. Coro de la Radio Neerlandesa, Orquesta del Concertgebouw de Amsterdam. Director: Eugen Jochum."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Pasión según San Mateo, BWV 244. Intérpretes: Peter Pears, Hermann Prey, August Messthaler, Heinz Blanckenburg, Elly Ameling, Marga Höffgen, Fritz Wunderlich. Coro Hymnus de Niños de Stuttgart, Orquesta de Cámara de Stuttgart. Director: Karl Münchinger."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Preludio para laúd, BWV 999. Intérprete: John Williams (guitarra)."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Suite nº 2 en Si menor BWV 1067. Intérpretes: Orquesta Filarmónica de Berlín. Director: Herbert von Karajan. "},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Suite nº 3 en Re may BWV 1068. Intérpretes: Orquesta Filarmónica de Berlín. Director: Herbert von Karajan. "},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Suite para cello, nº 1, BWV 1007. Intérprete: Anner Bylsma (cello)."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Suite para cello, nº 2, BWV 1008. Intérprete: Anner Bylsma (cello)."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Suite para cello, nº 3, BWV 1009. Intérprete: Anner Bylsma (cello)."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Suite para laúd, BWV 995. Intérprete: John Williams (guitarra)."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Suite para laúd, BWV 996. Intérprete: John Williams (guitarra)."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Suite-partita para laúd, BWV 997. Intérprete: John Williams (guitarra)."},
    {"data" : "Bach, Johann Sebastian (1685–1750) – Tocata en Do mayor para órgano. Intérpretes: Gaston Litaize (órgano) – Interpretada en el órgano Schwenkedel de la Abadía San Pedro de Solesmes."},
    {"data" : "Bach, Philipp Emmanuel (1714–1788) – Concierto para clavicémbalo, fortepiano y orquesta en Mi bemol mayor. Intérpretes: Li Stadelmann, Fritz Neumeyer y el Conjunto Instrumental de la Schola Cantorum Basiliensis, Director: August Wenzinger."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Concierto para piano nº 4, en Sol mayor, Op. 58. Intérpretes: Walter Gieseking y Orquesta Philharmonia. Director: Herbet von Karajan."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Concierto para piano nº 5, en Mi bemol mayor, Op. 738 “Emperador”. Intérpretes: Walter Gieseking (piano) y Orquesta Philharmonia. Director: Herbet von Karajan."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Concierto para piano nº 5, en Mi bemol mayor, Op. 738 “Emperador”. Intérpretes: Claudio Arrau (piano) y Orquesta del Estado de Dresde. Director: Sir Colin Davis."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Cristo en el Monte de los Olivos, Op. 85. Intérpretes: María Venutti (soprano), Keith Lewis (tenor) y Michel Brodard (bajo). Gächinger Kantorei y Bach-Collegium, Stuttgart. Director: Helmuth Rillling."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Cuarteto nº 15 en La menor Op. 132 para cuerdas. Intérprete: Cuarteto Yale."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Fidelio. Intérpretes: Wolfgang Windgassen, Alfred Poell, Gottlob Frick, Rudolf Schock, Marta Mödl y Sena Jurinac. Coro de la Ópera del Estado de Viena y Orquesta Filarmónica de Viena. Director: Wilhelm Furtwängler."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Misa en Do mayor, Op. 86. Intérpretes: Christiane Eda-Pierre (soprano), Patricia Payne (contralto), Robert Tear (tenor) y Kurt Moll (bajo). Coro y Orquesta Sinfónica de Londres. Director: Sir Colin Davis."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Missa Solemnis, Op. 123. Intérpretes: Anna Tommova-Sintow (soprano), Patricia Payne (contralto), Robert Tear (tenor) y Robert Lloyd (bajo). Coro y Orquesta Sinfónica de Londres. Director: Sir Colin Davis."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Obertura de Coriolano, Op. 62. Orquesta Filarmónica de Viena. Director: Wilhelm Furtwängler."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Obertura Leonora nº 2, Op. 72. Orquesta Filarmónica de Viena. Director: Wilhelm Furtwängler. "},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Septeto para violín, viola, violoncelo, clarinete, trompa, fagot, doble bajo, Op. 20. Intérpretes: integrantes del Octeto Filarmónico de Berlín."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sexteto para dos trompas y cuarteto de cuerdas, Op. 81b. Intérpretes: integrantes del Octeto Filarmónico de Berlín."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sinfonía nº 1, en Do mayor, Op. 21. Intérpretes: Orquesta Filarmónica de Viena. Director: Félix Weingartner."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sinfonía nº 2, en Re mayor, Op. 36. Intérpretes: Orquesta Sinfónica de Londres. Director: Félix Weingartner."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sinfonía nº 3, en Mi bemol mayor, Op. 55 “Heroica”. Intérpretes: Orquesta Filarmónica de Eslovaquia. Director: Zdenek Koslar."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sinfonía nº 4, en Si bemol mayor, Op. 60 (inicio). Intérpretes: Orquesta Filarmónica de Eslovaquia. Director: Henry Adolph."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sinfonía nº 7, en La mayor, Op. 92. Intérpretes: Orquesta Filarmónica de Eslovaquia. Director: Libor Pesek."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sinfonía nº 8, en Fa mayor, Op. 93. Intérpretes: Orquesta Filarmónica de Eslovaquia. Director: Henry Adolph."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sinfonía nº 9 “Sinfonía Coral” en Re menor, Op. 125. Intérpretes: Elizabeth Schwarzkopf, Elizabeth Höngen, Hans Hopf, Otto Edelman. Coro y Orquesta de los Festivales de Bayreuth. Director: Wilhelm Furtwängler."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sonata para piano n° 8 en Do menor, Op. 13 “Patética”. Intérprete: Wilhelm Kempff."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sonata para piano n° 14 en Do sostenido menor, Op. 27 n° 2 “Claro de luna”. Intérprete: Wilhelm Kempff."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sonata para piano n° 15 en Re mayor, Op. 28 “Pastoral”. Intérprete: Wilhelm Kempff."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sonata para piano n° 17 en Re menor, Op. 31 n° 2 “Tempestad”. Intérprete: Wilhelm Kempff."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sonata para piano n° 21 en Do mayor, Op. 5 “Waldstein”. Intérprete: Wilhelm Kempff."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sonata para piano n° 23 en Fa menor, Op. 57 “Appasionata”. Intérprete: Wilhelm Kempff."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sonata para piano n° 24 en Fa sostenido mayor, Op. 78. Intérprete: Wilhelm Kempff."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sonata para piano n° 25 en Sol mayor, Op. 79. Intérprete: Wilhelm Kempff."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sonata para piano n° 26 en Mi bemol mayor, Op. 81a “Los adioses”. Intérprete: Wilhelm Kempff."},
    {"data" : "Beethoven, Ludwig van (1770–1827) – Sonata para piano n° 28 en La menor, Op. 1011. Intérprete: Wilhelm Kempff."},
    {"data" : "Beethoven, Ludwig van (1779–1827) – Trío para piano en Si bemol mayor, Op. 97, “Archiduque”. Intérpretes: Trío de Trieste, Darío De Tosa (piano), Renato Zanettovich (violín), Libero Lana (violoncello), "},
    {"data" : "Berlioz, Héctor (1803–1869) – Sinfonía fantástica, Op. 14, “Sueño de una noche de aquelarre”. Orquesta Sinfónica de la Radio de Berlín. Director: Albert von Cammus."},
    {"data" : "Boccherini, Luigi (1743–1805) – Minueto del Quinteto Op. 13, n° 5. Intérpretes: Los Solistas de Zagreb. Director: Antonio Janigro."},
    {"data" : "Brahms, Johannes (1833–1897) – Danza húngara nº 1 en Sol menor. Orquesta Filarmónica de Viena. Director: Wilhelm Furtwängler."},
    {"data" : "Brahms, Johannes (1833–1897) – Danza húngara nº 10 en Fa mayor. Orquesta Filarmónica de Viena. Director: Wilhelm Furtwängler."},
    {"data" : "Brahms, Johannes (1833–1897) – Danza húngara nº 3 en Fa mayor. Orquesta Filarmónica de Viena. Director: Wilhelm Furtwängler."},
    {"data" : "Brahms, Johannes (1833–1897) – Sinfonía nº 1 en Do menor, Op. 68. Orquesta Filarmónica de Viena. Director: Wilhelm Furtwängler."},
    {"data" : "Brahms, Johannes (1833–1897) – Sinfonía nº 1 en Do menor, Op. 68. Orquesta Filarmónica de Berlín. Director: Wilhelm Furtwängler."},
    {"data" : "Brahms, Johannes (1833–1897) – Sinfonía nº 2 en Re mayor, Op. 73. Orquesta Filarmónica de Viena. Director: Wilhelm Furtwängler."},
    {"data" : "Brahms, Johannes (1833–1897) – Sinfonía nº 3 en Fa mayor, Op. 90. Orquesta Filarmónica de Viena. Director: Wilhelm Furtwängler."},
    {"data" : "Brahms, Johannes (1833–1897) – Sinfonía nº 4 en Mi menor, Op. 98. Orquesta Filarmónica de Viena. Director: Wilhelm Furtwängler."},
    {"data" : "Brahms, Johannes (1833–1897) – Variaciones sobre un tema de Haydn, Op. 56a, “St. Antoni Chorale”. Orquesta Filarmónica de Viena. Director: Wilhelm Furtwängler."},
    {"data" : "Canto Gregoriano – Agnus Dei IV. Intérpretes: Coro de los Monjes de la Abadía de San Pedro de Solesmes, Director Dom Joseph Gajard, OSB."},
    {"data" : "Canto Gregoriano – Comunión Jerusalem (4º). Intérpretes: Coro de los Monjes de la Abadía de San Pedro de Solesmes, Director Dom Joseph Gajard, OSB."},
    {"data" : "Canto Gregoriano – Comunión Pueri hebraeorum (4º). Intérpretes: Coro de los Monjes de la Abadía de San Pedro de Solesmes, Director Dom Joseph Gajard, OSB."},
    {"data" : "Canto Gregoriano – Gloria III. Intérpretes: Coro de los Monjes de la Abadía de San Pedro de Solesmes, Director Dom Joseph Gajard, OSB."},
    {"data" : "Canto Gregoriano – Himno Hostis Herodes (3º). Intérpretes: Coro de los Monjes de la Abadía de San Pedro de Solesmes, Director Dom Joseph Gajard, OSB."},
    {"data" : "Canto Gregoriano – Himno Salve festa dies (4º). Intérpretes: Coro de los Monjes de la Abadía de San Pedro de Solesmes, Director Dom Joseph Gajard, OSB."},
    {"data" : "Canto Gregoriano – Introito Dominus dixit ad me (2º). Intérpretes: Coro de los Monjes de la Abadía de San Pedro de Solesmes, Director Dom Joseph Gajard, OSB."},
    {"data" : "Canto Gregoriano – Ofertorio Precatus est (8º). Intérpretes: Coro de los Monjes de la Abadía de San Pedro de Solesmes, Director Dom Joseph Gajard, OSB."},
    {"data" : "Canto Gregoriano – Responsorio Judaea et Jerusalem (4º). Intérpretes: Coro de los Monjes de la Abadía de San Pedro de Solesmes, Director Dom Joseph Gajard, OSB."},
    {"data" : "Canto Gregoriano – Responsorio Tenebrae facte sunt (7º). Intérpretes: Coro de los Monjes de la Abadía de San Pedro de Solesmes, Director Dom Joseph Gajard, OSB."},
    {"data" : "Chopin, Frédéric (1810–1849) – Nocturno, Op. 15 en Fa mayor nº 1. Orquesta Sinfónica de la Radio de Berlín. Director: Albert von Cammus."},
    {"data" : "Corelli, Arcangelo (1653–1713) – Zarabanda, Giga y Badinerie para conjunto de cuerdas. Intérpretes: Los Solistas de Zagreb. Director: Antonio Janigro."},
    {"data" : "D’Andrieu, Jean François (1682–1738) – Misa Solemne de San Huberto para trompas de caza y órgano. Intérpretes: Marie-Claire Alain tocando en los Órganos de la Catedral de Meaux; Ensemble Rallye Louvarts de París."},
    {"data" : "Delalande, Michel R. (1675–1726) – Sinfonía y Cuarta Suite en Re mayor para trompeta y orquesta. Intérpretes: Adolf Scherbaum (trompeta) y Orquesta de Cámara Paul Kuentz de París, Director: Paul Kuentz."},
    {"data" : "Di Lasso, Orlando (1532–1594) – Lágrimas de San Pedro. Intérpretes: Conjunto vocal Ars Nova. Director: Bo Holten. "},
    {"data" : "Dvorak, Antonin (1841–1904) – Serenata para cuerdas, Op. 22. Orquesta Filarmónica de Radio Berlín. Director: Franz Aaron Kiendrich."},
    {"data" : "Fasch, Johann Freidrich (1688–1758) – Sonata para flauta traversa, dos flautas dulces y continuo. Intérpretes: Gustav Scheck, Verónica Hampe, Hans Linde, Johannes Koch y Eduard Müller."},
    {"data" : "Franck, César (1822–1890) – Música para órgano: Pieza heroica en Si menor. Intérprete: Feike Asma. Grabado en la Antigua Iglesia de Amsterdam."},
    {"data" : "Franck, César (1822–1890) – Música para órgano: Coral n° 1 en Mi mayor. Intérprete: Feike Asma. Grabado en la Antigua Iglesia de Amsterdam."},
    {"data" : "Franck, César (1822–1890) – Música para órgano: Coral n° 2 en Si menor. Intérprete: Feike Asma. Grabado en la Antigua Iglesia de Amsterdam."},
    {"data" : "Franck, César (1822–1890) – Música para órgano: Coral n° 3 en La menor. Intérprete: Feike Asma. Grabado en la Antigua Iglesia de Amsterdam."},
    {"data" : "Grieg, Edouard (1843–1907) – Vals, Op. 38 nº 7. Orquesta Filarmónica de Radio Berlín. Director: Franz Aaron Kiendrich."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Alleluya del Oratorio “El Mesías”. Intérpretes: Orquesta de Cámara y Coro de la Asociación St. Elisabeth, Director: Reinhard Munz."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Concerto grosso en Sol mayor, Op. 3 nº 3. Intérpretes: Heinz Holliger (oboe), Kenneth Sillito (violín) con The English Chamber Orchestra, Director: Raymond Leppard."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Concierto en Fa mayor para órgano, Op. 4, nº 4. Intérpretes: Eduard Müller (órgano) y el Conjunto Instrumental de la Schola Cantorum Basiliensis, Director: August Wenzinger."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Concierto en Si bemol mayor para órgano, Op. 4, nº 2. Intérpretes: Eduard Müller (órgano) y el Conjunto Instrumental de la Schola Cantorum Basiliensis, Director: August Wenzinger."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Concierto en Si mayor para oboe, cuerdas y continuo, nº 1. Intérpretes: Heinz Holliger (oboe), Kenneth Sillito (violín) con The English Chamber Orchestra, Director: Raymond Leppard."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Concierto en Si mayor para oboe, cuerdas y continuo, nº 2. Intérpretes: Heinz Holliger (oboe), Kenneth Sillito (violín) con The English Chamber Orchestra, Director: Raymond Leppard."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Concierto en Sol menor para órgano, Op. 4, nº 1. Intérpretes: Eduard Müller (órgano) y el Conjunto Instrumental de la Schola Cantorum Basiliensis, Director: August Wenzinger."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Concierto en Sol menor para órgano, Op. 4, nº 3. Intérpretes: Eduard Müller (órgano) y el Conjunto Instrumental de la Schola Cantorum Basiliensis, Director: August Wenzinger."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Concierto en Sol menor para oboe, cuerdas y continuo, nº 3. Intérpretes: Heinz Holliger (oboe), Kenneth Sillito (violín) con The English Chamber Orchestra, Director: Raymond Leppard."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Concierto para trompeta y órgano en Re menor. Intérpretes. Maurice André (trompeta) y English Chamber Orchestra. Director: Sir Charles Mackerras."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Música acuática. Intérpretes: Orquesta Sinfónica de Nürmberg, Director: Hanspeter Gmür."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Música para los reales fuegos de artificio. Intérpretes: Orquesta Sinfónica de Nürmberg, Director: Othmar F. Maga."},
    {"data" : "Haendel, Georg Friedrich (1685–1759) – Sonata a cinco en Si mayor para violín solista, cueras y continuo. Intérpretes: Kenneth Sillito (violín) con The English Chamber Orchestra, Director: Raymond Leppard."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Andante con variaciones en F-moll para piano. Intérpretes: Jörg Demus (piano) y el Collegium Aureum, Director: Franz-Joseph Maier."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Ave regina caelorum. Intérpretes: Orquesta de Cámara y Coro de la Asociación St. Elisabeth, Director: Reinhard Munz."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Concierto en D-dur para piano. Intérpretes: Jörg Demus (piano) y el Collegium Aureum, Director: Franz-Joseph Maier."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Concierto en Do mayor para órgano y cuerdas, nº 3. Intérpretes: E. Power Bigg (órgano) y la Orquesta Sinfónica Columbia, Director: Zoltan Rozsnyai."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Concierto en Do mayor para órgano, cuerdas, oboe y cornos, nº 1. Intérpretes: E. Power Bigg (órgano) y la Orquesta Sinfónica Columbia, Director: Zoltan Rozsnyai."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Concierto en Do mayor para órgano, cuerdas, trompetas y timbales, nº 2. Intérpretes: E. Power Bigg (órgano) y la Orquesta Sinfónica Columbia, Director: Zoltan Rozsnyai."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Concierto en F-major, nº 4, para lira, dos violines, dos violas, cello y dos cornos. Intérpretes: Württemberg Chamber Orchestra, Heilbronn, Director: Jörg Faeber."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Concierto en Mi bemol mayor para trompeta y orquesta. Intérpretes: Walter Gleisle (trompeta) y Orquesta Pro Música de Stuttgart, Director: Rolf Reinhardt."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Concierto en Re mayor para corno y orquesta. Intérpretes: Kart Arnold (corno) y Orquesta Pro Música de Stuttgart, Director: Rolf Reinhardt."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Concierto en Sol mayor, nº 2, para lira, dos violines, dos violas, cello y dos cornos. Intérpretes: Württemberg Chamber Orchestra, Heilbronn, Director: Jörg Faeber."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Cuarteto para cuerdas en Do mayor nº 77, Op. 76 nº 3, “Emperador”. Intérpretes: Cuarteto Koeckert."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Cuarteto para cuerdas en Fao mayor nº 17, Op. 3 nº 5, “Serenata”. Intérpretes: Cuarteto Végh."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Cuarteto para cuerdas en Re mayor nº 677, Op. 64 nº 5, “La alondra”. Intérpretes: Cuarteto Loewenguth."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Missa Solemnis en Si bemol mayor “Harmoniemesse”. Intérpretes: Christiane Sorell, Maura Moreira, Kurt Equiluz, Peter Wimberger. Coro de Cámara “Akademie”. Orquesta de la Ópera del Estado de Viena. Director: George Barati."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Oratorio Die Jahreszeiten (Las Estaciones). Intérpretes: Gundula Janowitz, Peter Schreier, Marti Talvella; Wiener Singverein und Wiener Symphoniker, Director: Karl Böhm."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Oratorio Las siete últimas palabras de Cristo. Grabado en el Salón Mozart de Viena en enero de 1962. Intérpretes: Virginia Babikian, Eunice Alberts, Ina Dressel, John van Kesteren, Otto Wiener; Coro de la Academia de Viena y Orquesta de la Ópera del Estado de Viena, Director: Hermann Scherchen."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Oratorio La Creación. Intérpretes: Teresa Stich-Randall, Antón Dermota, Anny Felbermayer, Paul Schoeffler, Frederick Guthrie; Coroso y Orquesta de la Ópera del Estado de Viena, Director: Mario Rossi."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Serenata del Cuarteto de cuerdas Op. 3, n° 5. Intérpretes: Los Solistas de Zagreb. Director: Antonio Janigro."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sinfonía Concertante en Si bemol mayor, Op. 84, para oboe, corno, violín y cello. Intérpretes: Württemberg Chamber Orchestra, Heilbronn, Director: Jörg Faeber."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sinfonía en D-dur nº 73, “La Chasse”. Intérpretes: Orquesta Philharmonia Hungarica, Director: Antal Dorati."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sinfonía en G-dur nº 92, “Oxford”. Intérpretes: Orquesta Philharmonia Hungarica, Director: Antal Dorati."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sinfonía en Mi bemol mayor, nº 103, “Redoble de timbales”. Intérpretes: Camerata Académica del Mozarteum de Salzburgo, Director: Bernhard Paumgartner."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sinfonía en Re mayor, nº 101, “El reloj”. Intérpretes: Orquesta Sinfónica de la Radio de Berlín, Director: Rolf Kleinert."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sinfonía en Sol mayor, nº 100, “Militar”. Intérpretes: Orquesta del Gewandhaus de Leipzig, Director: Otmar Suitner."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sinfonía en Sol mayor, nº 100, “Militar”. Intérpretes: Camerata Académica del Mozarteum de Salzburgo, Director: Bernhard Paumgartner."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sinfonía Sturm und Drang en Do mayor, nº 48, “Maria Theresia”. Intérpretes: Orquesta Sinfónica de la Radio de Zagreb, Director: Antonio Janigro."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sinfonía Sturm und Drang en Fa menor, nº 49, “La Passione”. Intérpretes: Orquesta Sinfónica de la Radio de Zagreb, Director: Antonio Janigro."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sinfonía Sturm und Drang en Si mayor, nº 46. Intérpretes: Orquesta Sinfónica de la Radio de Zagreb, Director: Antonio Janigro."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sinfonía Sturm und Drang en Sol mayor, nº 47. Intérpretes: Orquesta Sinfónica de la Radio de Zagreb, Director: Antonio Janigro."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Sonata en Fa mayor para piano. Intérpretes: Jörg Demus (piano) y el Collegium Aureum, Director: Franz-Joseph Maier."},
    {"data" : "Haydn, Franz Joseph (1732–1809) – Trío para piano n° 4 en Mi mayor. Intérpretes: Trío de Trieste, Darío De Tosa (piano), Renato Zanettovich (violín), Libero Lana (violoncello),"},
    {"data" : "Hertel, Johann Wilhelm (1727–1789) – Concierto para trompeta en Mi bemol mayor. Intérpretes. Maurice André (trompeta) y English Chamber Orchestra. Director: Sir Charles Mackerras. "},
    {"data" : "Hoffmann, Johann (1770–1842) – Concierto para mandolina y orquesta en Re mayor. Intérpretes: Elfriede Kunschak (mandolina) y Orquesta Pro Música de Viena, Director Vinzenz Hladky."},
    {"data" : "Hummel, Johann Nepomuk (1778–1837) – Concierto para mandolina y orquesta en Re mayor. Intérpretes: Edith Baue-Slais (mandolina) y orquesta Pro Música de Viena, Director: Vinzenz Hladky."},
    {"data" : "Humperdinck, Engelbert (1854–1921) – Hänsel y Gretel. Intérpretes: Marianne Schech, Gisela Litz, Rita Streich, Horst Günther, Res Fischer, Elisabeth Lindermeier, Bruno Brückmann; Coro Femenino de Radio de Baviera, Orquesta Filarmónica de München, Director: Fritz Lehmann."},
    {"data" : "Krommer, Franz (1759–1831) – Concierto para clarinete Op. 36. Intérpretes: Kálmán Berkes (clarinete) y Orquesta Sinfónica Nikolaus Esterházy. Director: Kálmán Berkes. "},
    {"data" : "Krommer, Franz (1759–1831) – Concierto para dos clarinetes Op. 35. Intérpretes: Kálmán Berkes y Kaori Tsutsui (clarinetes) y Orquesta Sinfónica Nikolaus Esterházy. Director: Kálmán Berkes. "},
    {"data" : "Krommer, Franz (1759–1831) – Concierto para dos clarinetes Op. 91. Intérpretes: Kálmán Berkes y Tomoko Takashima (clarinetes) y Orquesta Sinfónica Nikolaus Esterházy. Director: Kálmán Berkes."},
    {"data" : "Liszt, Franz (1811–1886) – Dos leyendas – San Francisco de Asís predica a los pájaros S 175. Intérprete: Nikolai Demidenko (piano). "},
    {"data" : "Liszt, Franz (1811–1886) – Dos leyendas – San Francisco de Paula pasea sobre las olas S 175. Intérprete: Nikolai Demidenko (piano). "},
    {"data" : "Liszt, Franz (1811–1886) – Preludios. Orquesta Filarmónica de Berlín. Director: Herbet von Karajan."},
    {"data" : "Liszt, Franz (1811–1886) – Rapsodia húngara nº 5, en Mi menor. Orquesta Filarmónica de Berlín. Director: Herbet von Karajan."},
    {"data" : "Liszt, Franz (1811–1886) – Scherzo y Marcha, S 177. Intérprete: Nikolai Demidenko (piano)."},
    {"data" : "Liszt, Franz (1811–1886) – Sonata para piano, S 178. Intérprete: Nikolai Demidenko (piano). "},
    {"data" : "Loewe, Carl (1796–1869) – Frauenliebe, Op. 60. Intérpretes: Brigitte Fassbänder (mesosoprano) y Cord Garben (piano)."},
    {"data" : "Loewe, Carl (1796–1869) – Lieder. Con textos de Goethe, Heine y Rückert. Intérpretes: Brigitte Fassbänder (mesosoprano) y Cord Garben (piano)."},
    {"data" : "Mendelssohn, Félix (1809–1847) – Sinfonía nº 5 en Re mayor, Op. 37, “La Reforma andante”. Orquesta Filarmónica de Radio Berlín. Director: Franz Aaron Kiendrich."},
    {"data" : "Monteverde, Claudio (1567–1643) – Madrigales y Conciertos: A Dio, florida bella, Volumen VI de Madrigales (Venecia – 1614), para Sopranos, Tenor, Barítono y Bajo. Intérpretes: Conjunto Leonhard y Coro Monteverde de Hamburgo; Director: Jürgen Jürgens."},
    {"data" : "Monteverde, Claudio (1567–1643) – Madrigales y Conciertos: Altri canti d’ amor, Volumen VIII de Madrigales (Venecia – 1638), para Sopranos, Tenor, Barítono y Bajo. Intérpretes: Conjunto Leonhard y Coro Monteverde de Hamburgo; Director: Jürgen Jürgens."},
    {"data" : "Monteverde, Claudio (1567–1643) – Madrigales y Conciertos: Amor che deggio far, Volumen VII de Madrigales (Venecia – 1619), para Sopranos, Tenor, Barítono y Bajo. Intérpretes: Conjunto Leonhard y Coro Monteverde de Hamburgo; Director: Jürgen Jürgens."},
    {"data" : "Monteverde, Claudio (1567–1643) – Madrigales y Conciertos: Hor che’l ciel e la terra, Volumen VIII de Madrigales (Venecia – 1638), para Sopranos, Tenor, Barítono y Bajo. Intérpretes: Conjunto Leonhard y Coro Monteverde de Hamburgo; Director: Jürgen Jürgens."},
    {"data" : "Monteverde, Claudio (1567–1643) – Madrigales y Conciertos: Presso un Fiume tranquillo, Volumen VI de Madrigales (Venecia – 1614), para Sopranos, Tenor, Barítono y Bajo. Intérpretes: Conjunto Leonhard y Coro Monteverde de Hamburgo; Director: Jürgen Jürgens."},
    {"data" : "Monteverde, Claudio (1567–1643) – Madrigales y Conciertos: Questi Vaghi Concerti, Volumen V de Madrigales (Mantua – 1605), para Sopranos, Tenor, Barítono y Bajo. Intérpretes: Conjunto Leonhard y Coro Monteverde de Hamburgo; Director: Jürgen Jürgens."},
    {"data" : "Monteverde, Claudio (1567–1643) – Madrigales y Conciertos: Qui rise, o Tirsi, Volumen VI de Madrigales (Venecia – 1614), para Sopranos, Tenor, Barítono y Bajo. Intérpretes: Conjunto Leonhard y Coro Monteverde de Hamburgo; Director: Jürgen Jürgens."},
    {"data" : "Mouret, Jean Joseph (1682–1738) – Fanfarrias. Intérpretes: Adolf Scherbaum (trompeta) y Orquesta de Cámara Paul Kuentz de París, Director: Paul Kuentz."},
    {"data" : "Mouret, Jean Joseph (1682–1738) – Primera Suite en Re mayor. Intérpretes: Adolf Scherbaum (trompeta) y Orquesta de Cámara Paul Kuentz de París, Director: Paul Kuentz."},
    {"data" : "Mouret, Jean Joseph (1682–1738) – Segunda Suite en Fa mayor. Intérpretes: Adolf Scherbaum (trompeta) y Orquesta de Cámara Paul Kuentz de París, Director: Paul Kuentz."},
    {"data" : "Mouret, Jean Joseph (1682–1738) – Sinfonías. Intérpretes: Adolf Scherbaum (trompeta) y Orquesta de Cámara Paul Kuentz de París, Director: Paul Kuentz."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Adagio para violín en Mi mayor, K. 261. Intérpretes: Henry Szeryng (violín) con la New Philharmonia Orchestra, Director: Alexander Gibson."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Alemanda en Do menor y Courante en Mi bemol mayor para piano, K. 399. Intérpretes: Jörg Demus (piano) que utiliza un piano Antón Walter de 1785."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Alma Dei creatoris, K. 277. Intérpretes: Orquesta de Cámara y Coro de la Asociación St. Elisabeth, Director: Reinhard Munz."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Andante para flauta y orquesta en Do mayor, K. 315. Intérpretes: Jean Pierre Rampal (flauta) con la Orquesta Sinfónica de Viena, Director: Theodor Guschlbauer."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Ave Verum Corpus K 618. Intérpretes: Barbara Schilick (soprano), Elisabeth von Magnus (contralto), Paul Agnew (tenor) y Matthijs Mesdag (bajo). Coro y Orquesta Barroca de Amsterdam. Director: Ton Koopman."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Bastian y Bastiana. Juego pastoril alemán en un acto. Intérpretes: Rita Streich, Richard Holm, Toni Blankenheim, Herbert List con la Orquesta de Cámara de München, Director: Christoph Stepp."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto en Do mayor, nº 8 para piano y orquesta, K. 246. Intérpretes: Robert Vieron-Lacroix (piano); Orquesta de Cámara de la Radiodifusión del Sarre, Director: Karl Ristempart."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto en Mi bemol mayor para corno y orquesta, K. 447. Intérpretes: Albert Linder (corno) y Orquesta de la Ópera del Estado de Viena, Director: Hans Swarowsky."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto en Mi bemol mayor para corno y orquesta, K. 495. Intérpretes: Albert Linder (corno) y Orquesta de la Ópera del Estado de Viena, Director: Hans Swarowsky."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto en Mi bemol mayor para corno y orquesta, K. 417. Intérpretes: Albert Linder (corno) y Orquesta de la Ópera del Estado de Viena, Director: Hans Swarowsky."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto en Mi bemol mayor para piano y orquesta de cuerdas, K. 107, nº 3, sobre Johann Christian Bach. Intérpretes: Robert Veyron-Lacroix (piano); Orquesta de Cámara de la Radiodifusión del Sarre, Director: Karl Ristempart."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto en Re mayor para corno y orquesta, K. 412. Intérpretes: Albert Linder (corno) y Orquesta de la Ópera del Estado de Viena, Director: Hans Swarowsky."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto en Re mayor para piano y orquesta de cuerdas, K. 107, nº 1, sobre Johann Christian Bach. Intérpretes: Robert Veyron-Lacroix (piano); Orquesta de Cámara de la Radiodifusión del Sarre, Director: Karl Ristempart."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto en Re mayor para piano y orquesta de cuerdas, K. 107, nº 2, sobre Johann Christian Bach. Intérpretes: Robert Veyron-Lacroix (piano); Orquesta de Cámara de la Radiodifusión del Sarre, Director: Karl Ristempart."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto nº 3 en Sol mayor, K. 216 para violín y orquesta. Intérpretes: Anne-Sophie Mutter (violín) y Orquesta Filarmónica de Berlín, Director: Herbert von Karajan."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto nº 5 en La mayor, K. 219 para violín y orquesta. Intérpretes: Anne-Sophie Mutter (violín) y Orquesta Filarmónica de Berlín, Director: Herbert von Karajan."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto para corno y orquesta en Mi bemol mayor, nº 3, K. 447. Intérpretes: Albert Linder (corno) y la Orquesta de la Ópera del Estado de Viena, Director: Hans Swarowsky."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto para corno y orquesta en Mi bemol mayor, nº 4, K. 495. Intérpretes: Albert Linder (corno) y la Orquesta de la Ópera del Estado de Viena, Director: Hans Swarowsky."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto para corno y orquesta en Mi bemol mayor, nº 2, K. 417. Intérpretes: Albert Linder (corno) y la Orquesta de la Ópera del Estado de Viena, Director: Hans Swarowsky."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto para corno y orquesta en Re mayor, nº 1, K. 412. Intérpretes: Albert Linder (corno) y la Orquesta de la Ópera del Estado de Viena, Director: Hans Swarowsky."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto para fagot y orquesta en Si bemol mayor, K. 191. Intérpretes: Paul Hongne (fagot) y la Orquesta Sinfónica de Bamberg, Director: Theodor Guschlbauer."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto para flauta y orquesta en Sol mayor, nº 1, K. 313. Intérpretes: Jean Pierre Rampal (flauta) con la Orquesta Sinfónica de Viena, Director: Theodor Guschlbauer."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto para flauta y orquesta en Re mayor, nº 2, K. 314. Intérpretes: Jean Pierre Rampal (flauta) con la Orquesta Sinfónica de Viena, Director: Theodor Guschlbauer."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto para violín en Sol mayor, K. 216. Intérpretes: Henry Szeryng (violín) con la New Philharmonia Orchestra, Director: Alexander Gibson."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Concierto para violín en Re mayor, K. 218. Intérpretes: Henry Szeryng (violín) con la New Philharmonia Orchestra, Director: Alexander Gibson."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Così fan tutte. Libreto de Lorenzo Da Ponte. Intérpretes: Elisabeth Schwarzkopff, Christa Ludwig, Hanny Steffek, Alfredo Kraus, Giuseppe Taddei, Walter Berry; Coro y Orquesta Philharmonia de Londres, Director: Karl Böhm."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Cuarteto para cuerdas en Re mayor, K. 499. Intérpretes: Cuarteto Melos."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Cuarteto para cuerdas en Re mayor, K. 575. Intérpretes: Cuarteto Melos."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Divertimento en Fa mayor, K. 138. Intérpretes: Los Solistas de Zagreb, Director: Antonio Janigro."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Divertimento en Fa mayor, K. 138, Sinfonía Salzburg nº 3. Intérpretes: Orquesta Filarmónica del Sud de Alemania. Director: Alberto Lizzio."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Divertimento en Re mayor, K. 136. Intérpretes: Los Solistas de Zagreb, Director: Antonio Janigro."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Divertimento en Re mayor, K. 136, Sinfonía Salzburg nº 1. Intérpretes: Orquesta Filarmónica del Sud de Alemania. Director: Alberto Lizzio."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Divertimento en Si bemol mayor, K. 137. Intérpretes: Los Solistas de Zagreb, Director: Antonio Janigro."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Divertimento en Si bemol mayor, K. 137, Sinfonía Salzburg nº 2. Intérpretes: Orquesta Filarmónica del Sud de Alemania. Director: Alberto Lizzio."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Don Giovanni. Libreto de Lorenzo Da Ponte. Intérpretes: Eberhard Wächter, Joan Sutherland, Luigi Alva, Gottlob Frick, Elisabeth Schwarzkopff, Giuseppe Taddei, Piero Capuccilli, Graziella Sciutti; Coro y Orquesta Philharmonia de Londres, Director: Carlo María Giulini."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Exsultate, Jubilate K 165. Intérpretes: Barbara Schilick (soprano), Elisabeth von Magnus (contralto), Paul Agnew (tenor) y Matthijs Mesdag (bajo). Coro y Orquesta Barroca de Amsterdam. Director: Ton Koopman."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Fantasía en Do menor para piano, K. 236. Intérpretes: Jörg Demus (piano) que utiliza un piano Antón Walter de 1785."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Fantasía en Do menor para piano, K. 475. Intérpretes: Jörg Demus (piano) que utiliza un piano Antón Walter de 1785."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Giga en Sol mayor para piano, K. 574. Intérpretes: Jörg Demus (piano) que utiliza un piano Antón Walter de 1785."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Idomeneo. Libreto de Giambattista Varseco. Intérpretes: Wieslaw Ochman, Peter Schreier, Edith Mattis, Julia Varady, Hermann Winkler, Eberhard Büchner, Siegfried Vogel; Coro de la Radio de Leipzig y Orquesta del Estado de Dresde, Director: Karl Böhm."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – La flauta mágica. Ópera alemana en dos actos. Intérpretes: Josef Greindl, Ernst Häflinger, Rita Streich, María Stader, Dietrich Fisher-Dieskau, Lisa Otto; Coro de Cámara RIAS, Coro de Motetes de Berlín y Orquesta Sinfónica RIAS, Director: Ferenc Fricsay."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Las bodas de Fígaro. Libreto de Lorenzo Da Ponte. Intérpretes: Hilde Gueden, Lisa Della Casa, Suzanne Danco, Cesare Siepi, Alfred Poell, Fernando Corena; Coro de la Ópera del Estado de Viena y Orquesta Filarmónica de Viena, Director: Erich Kleiber."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Laudate dominum, K. 339. Intérpretes: Orquesta de Cámara y Coro de la Asociación St. Elisabeth, Director: Reinhard Munz."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Laudate dominum, “Ad Vesperae de Dominica” K. 321. Intérpretes: Orquesta Academica de Salzburgo, Director: Ernst Hinreiner."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Marcha en Re mayor, K. 335, nº 1. Intérpretes: Orquesta del Mozarteum de Salzburgo, Director: Mladen Basic."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Marcha en Re mayor, K. 335, nº 2. Intérpretes: Orquesta del Mozarteum de Salzburgo, Director: Mladen Basic."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Minué en Re mayor para piano, K. 355. Intérpretes: Jörg Demus (piano) que utiliza un piano Antón Walter de 1785."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Misa en Do mayor, K. 317 De la coronación. Intérpretes: Orquesta de Cámara y Coro de la Asociación St. Elisabeth, Director: Reinhard Munz."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Misa en Do mayor K. 317, De la Coronación. Intérpretes: Barbara Schilick (soprano), Elisabeth von Magnus (contralto), Paul Agnew (tenor) y Matthijs Mesdag (bajo). Coro y Orquesta Barroca de Amsterdam. Director: Ton Koopman."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Misa en Do mayor, K. 317, De la coronación. Intérpretes: Gabriele Fuchs, Angelika Novak, Franz Sailer, Hartmut Müller. Coro Mozarteum y Orquesta Academica de Salzburgo, Director: Ernst Hinreiner."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Obertura Les petits riens, K. 299b. Intérpretes: Orquesta Sinfónica de la Radio de Baviera, Director: Ferdinand Leitner."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Pequeña música nocturna, K. 525. Intérpretes: Capella Istropolitana. Director: Libor Pesek."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Requiem, K. 626. Intérpretes: Wilma Lipp, Hilde Rössel-Majdan, Antón Dermota, Walter Berry con la Orquesta Filarmónica de Berlín, Director: Herbert von Karajan."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Requiem en Re menor, K. 626. Intérpretes: Anna Tommova-Sintow (soprano), Agnes Baltsa (contraltp), Werner Krenn (tenor) y José van Dam (bajo). Asociación Coral de Viena y Orquesta Filarmónica de Berlín. Director: Herbert von Karajan."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Rondó en La menor para piano, K. 511. Intérpretes: Jörg Demus (piano) que utiliza un piano Antón Walter de 1785."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Rondó para corno y orquesta en Mi bemol mayor, K. 371. Intérpretes: Georges Barboteu (corno) y la Orquesta Sinfónica de Bamberg, Director: Theodor Guschlbauer."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Selección de canciones recopiladas bajo el título general de “El Mozart cómico”. Intérpretes: Erika Köth, Peter Schreier, Hermann Prey y Walter Berry, Coro de Cámara de la Academia de Viena y Convivium Musicum de München, Director: Xaver Mayer."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Motete “Exsultate, jubilate“, K. 165. Intérpretes: Gabriele Fuchs, Robert Kuppelwieser. Camerata Academica de Salzburgo, Director: Ernst Hinreiner."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Serenata en Sol mayor, K. 525, “Una pequeña música nocturna”. Intérpretes: Camerata Bariloche, Director: Elías Khayat."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Serenata nº 9 en Re mayor, K. 320, “Serenata del Corno del Postillón”. Intérpretes: August Nowicki (corno) y Orquesta del Mozarteum de Salzburgo, Director: Mladen Basic."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Serenata Nocturno en Re mayor, K. 239. Intérpretes: Los Solistas de Zagreb, Director: Antonio Janigro."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Sinfonía Concertante para instrumentos de viento y orquesta en Mi bemol mayor, K. 297 b. Intérpretes: Orquesta Sinfónica de Bamberg, Director: Theodor Guschlbauer."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Sinfonía en Re mayor, nº 31, K. 297 “París”. Intérpretes: Orquesta Sinfónica de la Radio de Baviera, Director: Ferdinand Leitner."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Sinfonía nº 35 en Re mayor “Haffner”, K. 385. Intérpretes: Orquesta Filarmónica de Eslovaquia. Director: Zednek Kosler."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Sinfonía en Do mayor, nº 36, K. 425 “Linz”. Intérpretes: Orquesta Filarmónica de Eslovaquia. Director: Zednek Kosler."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Sinfonía en Do mayor, nº 36, K. 425 “Linz”. Intérpretes: Orquesta Sinfónica de la Radio de Baviera, Director: Ferdinand Leitner."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Sinfonía en Re mayor, nº 38, K. 504 “Praga”. Intérpretes: Orquesta Filarmónica de Berlín, Director: Herbert von Karajan."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Sinfonía en Mi bemol mayor, nº 39, K. 543. Intérpretes: Orquesta Filarmónica de Berlín, Director: Herbert von Karajan."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Sinfonía en Sol menor, nº 40, K. 550. Intérpretes: Orquesta de Cámara de Moscú, Director: Rudolf Barshai."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Sonata de Iglesia en Do mayor, K. 328. Intérpretes: Orquesta Academica de Salzburgo, Director: Ernst Hinreiner."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Sonata en Do mayor para piano, K. 330. Intérpretes: Jörg Demus (piano) que utiliza un piano Antón Walter de 1785."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Sonata en La mayor para piano, K. 331. Intérpretes: Jörg Demus (piano) que utiliza un piano Antón Walter de 1785."},
    {"data" : "Mozart, Wolfgang Amadeus (1756–1791) – Vísperas solemnes de confesores K 339. Intérpretes: Barbara Schilick (soprano), Elisabeth von Magnus (contralto), Paul Agnew (tenor) y Matthijs Mesdag (bajo). Coro y Orquesta Barroca de Amsterdam. Director: Ton Koopman."},
    {"data" : "Música del tiempo de la Reina Elisabeth I. Intérpretes: The Academy of Ancient Music. Director: Christppher Hogwood."},
    {"data" : "Música de la España Renacentista. Para voz, laúd, viola de mano, cítara y guitarra renacentista. Intérprete: Shirley Rumsey."},
    {"data" : "Música de la Italia Renacentista. Para voz, vihuelas, laúd y guitarra renacentista. Intérprete: Shirley Rumsey."},
    {"data" : "Música religiosa bizantino-eslava. Santísima Madre de Dios ¡Sálvanos! Intérpretes: Coro de la Catedral Ortodoxa Rusa de la Santísima Trinidad, Buenos Aires, Argentina."},
    {"data" : "Palestrina, Giovanni P. da (1524–1594) – Misa Salve Regina. Versión en vivo del 13 de agosto de 1998. Intérpretes: Coro de Cámara de Adrogué. Director: Marcelo Ortiz Rocca."},
    {"data" : "Quantz, Johann Joachim (1697–1773) – Trío sonata en Do mayor para flauta dulce, flauta traversa y bajo continuo. Intérpretes: Gustav Scheck, Verónica Hampe, Hans Linde, Johannes Koch y Eduard Müller."},
    {"data" : "Rossini, Gioacchino (1792–1868) – Sonata n° 5 para cuerdas en Mi bemol mayor Intérpretes: Los Solistas de Zagreb. Director: Antonio Janigro."},
    {"data" : "Rossini, Gioacchino (1792–1868) – Obertura de El barbero de Sevilla. Orquesta Sinfónica de Nueva York. Director: Thomas Schneider."},
    {"data" : "Rossini, Gioacchino (1792–1868) – Obertura de Guillermo Tell. Orquesta Filarmónica de Berlín. Director: Herbet von Karajan."},
    {"data" : "Rossini, Gioacchino (1792–1868) – Sonata n° 6 para cuerdas en Re mayor. Intérpretes: Los Solistas de Zagreb. Director: Antonio Janigro."},
    {"data" : "Schubert, Franz (1797–1828) – Cuarteto de cuerdas nº 15 en Sol mayor, Op. 161. Intérpretes: Cuarteto Konzerthaus de Viena."},
    {"data" : "Schubert, Franz (1797–1828) – Cuarteto de cuerdas en Do menor, Opus póstumo D 703. Intérpretes: Weller Quartet."},
    {"data" : "Schubert, Franz (1797–1828) – El canto del cisne. Intérpretes: Peter Schreier (tenor) y András Schiff (piano)."},
    {"data" : "Schubert, Franz (1797–1828) – Impromptus, Momentos musicales, Valses y Variaciones, Op. 90,4; Op. 94,4; Op. 142, 2; Op. 142, 3; Op. 9, D.718; Op. 90, 2, D.593. Intérpretes: Jörg Demus (piano)."},
    {"data" : "Schubert, Franz (1797–1828) – Impromptus Op. 90 D 899. Intérprete: Alfred Brendel (piano)."},
    {"data" : "Schubert, Franz (1797–1828) – Impromptus Op. 142 D 935. Intérprete: Alfred Brendel (piano)."},
    {"data" : "Schubert, Franz (1797–1828) – La bella molinera. Intérpretes: Fritz Wunderlich (tenor) y Hubert Giesen (piano)."},
    {"data" : "Schubert, Franz (1797–1828) – La bella molinera. Intérpretes: Peter Schreier (tenor) y András Schiff (piano)."},
    {"data" : "Schubert, Franz (1797–1828) – Obertura en Mi menor. Orquesta Sinfónica de la Radio de Berlín. Director: Albert von Cammus."},
    {"data" : "Schubert, Franz (1797–1828) – Quinteto de cuerdas en Do mayor, Op. 163 D 956. Intérpretes: Weller Quartet y Dietfried Gürtler."},
    {"data" : "Schubert, Franz (1797–1828) – Sinfonía nº 5 en Si bemol mayor, D.485. Intérpretes: Orquesta Filarmónica de Berlín, Director: Karl Böhm."},
    {"data" : "Schubert, Franz (1797–1828) – Sinfonía nº 8 en Si menor “Inconclusa”, D. 759. Intérpretes: Orquesta Filarmónica de Berlín, Director: Karl Böhm."},
    {"data" : "Schubert, Franz (1797–1828) – Sinfonía nº 9 en Do mayor, D. 944. Intérpretes: Orquesta del Estado de Dresde, Director: Karl Böhm."},
    {"data" : "Schubert, Franz (1797–1828) – Trío para cuerdas en Si bemol mayor, D-581. Intérpretes: Trío Grumiaux: Arthur Grumiaux, Georges Janzer y Eva Czako."},
    {"data" : "Schubert, Franz (1797–1828) – Trío para cuerdas en Si bemol mayor, D-4781. Intérpretes: Trío Grumiaux: Arthur Grumiaux, Georges Janzer y Eva Czako."},
    {"data" : "Schubert, Franz (1797–1828) – Trío para cuerdas en Si bemol mayor, D-898. Intérpretes: Beaux Arts Trío: Menahen Pressler, Daniel Guilet y Bernard Greenhouse."},
    {"data" : "Schubert, Franz (1797–1828) – Viaje de invierno. Intérpretes: Peter Schreier (tenor) y András Schiff (piano)."},
    {"data" : "Sibelius, Jean (1865–1957) – Concierto para violín y orquesta Op. 47 “Finlandia”. Intérpretes: Ruggiero Ricci y la Orquesta Sinfónica de Bochum, Director: Matthias Kuntzsch."},
    {"data" : "Smetana, Bedrich (1824–1884) – El Moldava. Orquesta Filarmónica de Berlín. Director: Herbet von Karajan."},
    {"data" : "Stamitz, Johann (1717–1757) – Concierto para clarinete y orquesta. Intérpretes: Sabine Meyer (clarinete) y Orquesta de la Academia de St. Matin in the Fields. Director: Iona Brown."},
    {"data" : "Stamitz, Karl (1746–1801) – Concierto para clarinete y orquesta, nº 3. Intérpretes: Sabine Meyer (clarinete) y Orquesta de la Academia de St. Matin in the Fields. Director: Iona Brown. (Topog. La Plata CD 2)."},
    {"data" : "Stamitz, Karl (1746–1801) – Concierto para clarinete y orquesta, nº 11. Intérpretes: Sabine Meyer (clarinete) y Orquesta de la Academia de St. Matin in the Fields. Director: Iona Brown."},
    {"data" : "Stamitz, Karl (1746–1801) – Concierto para clarinete y orquesta, nº 10. Intérpretes: Sabine Meyer (clarinete) y Orquesta de la Academia de St. Matin in the Fields. Director: Iona Brown."},
    {"data" : "Stamitz, Karl (1745–1801) – Concierto en D-major para viola y orquesta, nº 1. Intépretes: Ernst Wallfisch (viola) y la Württemberg Chamber Orchestra, Heilbronn, Director: Jörg Faeber."},
    {"data" : "Stamitz, Karl (1745–1801) – Sinfonía concertante para violín y viola con orquesta. Intérpretes: Susanne Lautenbacher (violín), Ernst Wallfisch (viola) y la Württemberg Chamber Orchestra, Heilbronn, Director: Jörg Faeber."},
    {"data" : "Strauss, Richard (1864–1949) – Ariadna en Naxos. Libreto de Hugo von Hoffmansthal. Intérpretes: Elisabeth Schwarzkopff, Rudolf Schock, Irmgard Seefried, Rita Streich; Orquesta Philharmonia, Director: Herbert von Karajan."},
    {"data" : "Strauss, Richard (1864–1949) – Así hablaba Zaratustra. Poema sinfónico, Op. 30. Intérpretes: Orquesta Filarmónica de Berlín, Director: Herbert von Karajan."},
    {"data" : "Strauss, Richard (1864–1949) – El caballero de la rosa. Libreto de Hugo von Hoffmansthal. Intérpretes: María Reining, Sena Jurinac, Ludwig Weber, Alfred Poell, Hilde Gueden, Walter Berry, Antón Dermota, Hilde Rössel-Majdan; Coros de la Orquesta del Estado de Viena, Orquesta Filarmónica de Viena, Director: Erich Kleiber."},
    {"data" : "Strauss, Richard (1864–1949) – Elektra. Intérpretes: Inge Borkh, Lisa Della Casa, Marilyn Horne, Jean Madeira, Kurt Böhme, Max Lorenz y Alois Pernerstorfer. Coro de la Ópera del Estado de Viena y Orquesta Filarmónica de Viena. Director: Dimitri Mitropoulos."},
    {"data" : "Strauss, Richard (1864–1949) – Las cuatro últimas canciones. Intérpretes: Kiri Te Kanawa (soprano) y Sir Georg Solti (piano). Orquesta Filarmónica de Viena. Director: Sir Georg Solti."},
    {"data" : "Strauss, Richard (1864–1949) – Obras corales para voces masculinas. Intérpretes: Renner Ensemble Regensburg. Director: Bernd Englbrecht."},
    {"data" : "Strauss, Richard (1864–1949) – Salomé. Intérpretes: Hildergard Behrens, Agnes Baltsa, Karl Walter Böhm, José van Dam, Gerhard Unger, Erich Kunz y Heinz Sednik. Orquesta Filarmónica de Viena. Director: Herbet von Karajan."},
    {"data" : "Strauss, Richard (1864–1949) – Una sinfonía alpina, Op. 64. Intérpretes: Orquesta del Estado de Sajonia, Director: Karl Böhm."},
    {"data" : "Strauss, Richard (1864–1949) – Una vida de héroe, Op. 40. Intérpretes: Orquesta del Estado de Dresde, Director: Karl Böhm."},
    {"data" : "Tartini, Giuseppe (1692–1770) – Concierto en La mayor para violín, cuerdas y continuo, D. 96. Intérpretes: Uto Ughi (violín) con I Solisti Veneti, Director: Claudio Scimone."},
    {"data" : "Tartini, Giuseppe (1692–1770) – Concierto en La menor para violín, cuerdas y continuo, D. 113. Intérpretes: Uto Ughi (violín) con I Solisti Veneti, Director: Claudio Scimone."},
    {"data" : "Tartini, Giuseppe (1692–1770) – Concierto en Mi menor para violín, cuerdas y continuo, D. 56. Intérpretes: Uto Ughi (violín) con I Solisti Veneti, Director: Claudio Scimone."},
    {"data" : "Telemann, Georg Philipp (1681–1767) – Concierto en Re mayor para trompeta, cuerdas y bajo continuo. Intérpretes: Adolf Scherbaum (trompeta) y orquesta Bach de Hamburgo, Director: Robert Stehli."},
    {"data" : "Telemann, Georg Philipp (1681–1767) – Concierto en Re mayor para trompeta, dos oboes y bajo continuo. Intérpretes: Adolf Scherbaum (trompeta) y orquesta Bach de Hamburgo, Director: Robert Stehli."},
    {"data" : "Telemann, Georg Philipp (1681–1767) – Concierto para corno de caza. Intérpretes: Ludwig Güttler (corno) y New Bach Collegium Musicum. Director: Max Pommer. "},
    {"data" : "Telemann, Georg Philipp (1681–1767) – Concierto para trompeta en Re mayor. Intérpretes. Maurice André (trompeta) y English Chamber Orchestra. Director: Sir Charles Mackerras."},
    {"data" : "Telemann, Georg Philipp (1681–1767) – Concierto en Sol mayor para flauta traversa, oboe, violín y bajo continuo. Intérpretes: Camerata Instrumentale de Hamburgo."},
    {"data" : "Telemann, Georg Philipp (1681–1767) – Concierto en Sol mayor para flauta dulce, oboe, violín y bajo continuo. Intérpretes: Camerata Instrumentale de Hamburgo."},
    {"data" : "Telemann, George Philipp (1681–1767) – Obertura para dos trompas,  cuerdas y bajo continuo. Intérpretes. Ab Koster y Jan Schröder (trompas) y el conjunto German Bach Soloists. Director: Helmut Winschermann."},
    {"data" : "Telemann, George Philipp (1681–1767) – Suite para dos trompetas, timbales, cuerdas y bajo continuo. Intérpretes. Wolfgang Basch y Albert Oesterle (trompetas) y el conjunto German Bach Soloists. Director: Helmut Winschermann. "},
    {"data" : "Telemann, George Philipp (1681–1767) – Suite para tres trompetas, cuerdas y bajo continuo. Intérpretes. Wolfgang Basch, Albert Oesterle y Otto Blasaditsch (trompetas) y el conjunto German Bach Soloists. Director: Helmut Winschermann."},
    {"data" : "Telemann, George Philipp (1681–1767) – Suite para trompeta, cuerdas y bajo continuo. Intérpretes. Wolfgang Basch (trompeta) y el conjunto German Bach Soloists. Director: Helmut Winschermann."},
    {"data" : "Tschaicovsky, Piotr Ilich (1840–1893) – Serenata en Do mayor, Op. 48. Intérpretes: Camerata Bariloche, Director: Elías Khayat."},
    {"data" : "Verdi, Giuseppe (1813–1901) – Aída. Intérpretes: María Callas, Richard Tucker, Fedora Barbieri, Tito Gobbi. Coro y Orquesta del Teatro Alla Scala de Milán. Director: Tullio Serafín."},
    {"data" : "Verdi, Giuseppe (1813–1901) – Nabucco. Selección. Intérpretes: Piero Capuccilli, Plácido Domingo, Ghena Dimitrova, Lucía Popp. Coro y Orquesta de la Ópera de Berlín. Director: Giuseppe Sinopoli."},
    {"data" : "Verdi, Giuseppe (1813–1901) – Obertura de La fuerza del destino. Orquesta Sinfónica de Nueva York. Director: Thomas Schneider."},
    {"data" : "Vivaldi, Antonio (1675–1741) – Concierto para dos cornos de caza, P. 321. Intérpretes: Músicos Praguenses y Symposium Musicum, Director: Ladislav Vachulka."},
    {"data" : "Vivaldi, Antonio (1675–1741) – Concierto para flautín, P. 79. Intérpretes: Músicos Praguenses y Symposium Musicum, Director: Ladislav Vachulka."},
    {"data" : "Vivaldi, Antonio (1675–1741) – Concierto para guitarra “Allegro”. Orquesta Sinfónica de la Radio de Berlín. Director: Albert von Cammus."},
    {"data" : "Vivaldi, Antonio (1675–1741) – Concierto para violín, P. 165. Intérpretes: Músicos Praguenses y Symposium Musicum, Director: Ladislav Vachulka."},
    {"data" : "Vivaldi, Antonio (1675–1741) – Concierto para violín, P. 405. Intérpretes: Músicos Praguenses y Symposium Musicum, Director: Ladislav Vachulka."},
    {"data" : "Vivaldi, Antonio (1675–1741) – La Cetra Op. 9 – Doce conciertos para violín y orquesta de cuerdas. Intérpretes: Reinhold Barchet (violín) y Orquesta de Cuerdas Pro Música de Stuttgart, Director: Rolf Reinhardt."},
    {"data" : "Von Bingen, Hildegard (1098–1179) – Himnos, Secuencias, Antífonas. Intérpretes: Oxford Camerata. Director: Jeremy Summerly."},
    {"data" : "Wagner, Richard (1813–1883) – Der Fliegende Holländer (El holandés errante). Intérpretes: Astrid Varnay, Hermann Uhde, Rudolf Lustig, Ludwig Weber, Elisabeth Schärtel, Josef Traxel; Coro y Orquesta de los Festivales de Bayreuth, 1955, Director: Joseph Keilberth."},
    {"data" : "Wagner, Richard (1813–1883) – Der Fliegende Holländer (El holandés errante). Intérpretes: Anja Silja, Josef Greibdl, Fritz Uhl, Franz Crass, Res Ficher, Georg Paskuda. Coro y Orquesta de los Festivales de Bayreuth, 1961, Director: Wolfgang Sawalisch."},
    {"data" : "Wagner, Richard (1813–1883) – Lohengrin. Intérpretes: James King, Gundula Janowitz, Gwyneth Jones, Thomas Stewart y Karl Riedderbusch. Coro y Orquesta Sinfónica de la Radio de Baviera. Director: Rafael Kubelik."},
    {"data" : "Wagner, Richard (1813–1883) – Los maestros cantores de Nürmberg. Intérpretes: Elisabeth Schwarzkopff, Otto Edelmann, Erich Kunz, Hans Hoppf, Gerhard Unger, Ira Malaniuk; Coro y Orquesta de los Festivales de Bayreuth, 1951, Director: Herbert von Karajan."},
    {"data" : "Wagner, Richard (1813–1883) – Parsifal. Intérpretes: Eberhard Wächter, Hans Hotter, Fritz Uhl, Walter Berry, Elisabeth Höngen y Christa Ludwig. Coro y Orquesta de la Ópera del Estado de Viena. Director: Herbert von Karajan."},
    {"data" : "Wagner, Richard (1813–1883) – Parsifal. Intérpretes: Wolfgang Windgassen, George London, Ludwig Weber, Hermann Uhde y Marta Mödl. Coro y Orquesta de los Festivales de Bayreuth. Director: Hans Knappertsbusch."},
    {"data" : "Wagner, Richard (1813–1883) – Parsifal. Intérpretes: Jess Thomas, George London, Martti Talvela,  Hans Hotter, Gustav Neidlinger, Irene Dalis. Coro y Orquesta de los Festivales de Bayreuth, 1962. Director: Hans Knappertsbusch."},
    {"data" : "Wagner, Richard (1813–1883) – Rienzi. Intérpretes: René Kollo, Siv Wennberg, Janis Martin, Theo Adam, Nikolaus Hillebrand, Peter Schreier. Coro y Orquesta del estado de Dresden. Director: Heinrich Hollreiser."},
    {"data" : "Wagner, Richard (1813–1883) – Tannhäuser. Intérpretes: Lauritz Melchior, Helen Traubel, Astrid Varnay, Herbert Janssen y Mihály Székely. Registro en vivo del 6 de marzo de 1948. Coro y Orquesta del Metropolitan Opera House de Nueva York. Director: Fritz Striedry."},
    {"data" : "Wagner, Richard (1813–1883) – Tannhäuser. Intérpretes: Wolfgang Windgassen, Josef Greindl, Eberhard Wächter, Gerard Stolze, Franz Crass, Georg Paskuda, Anja Silja, Else M. Gardelli. Coro y Orquesta de los Festivales de Bayreuth, 1962. Director: Wolfgang Sawalisch."},
    {"data" : "Weber, Carl María von (1786–1826) – Invitación a la danza, Op. 65, arreglo de Héctor Berlioz. Director: Herbet von Karajan."},
    {"data" : "Weber, Carl María von (1786–1826) – Oberon – Libreto de J. R. Planché. Intérpretes: Birgit Nilsson, Julia Hamari, Plácido Domingo, Hermann Prey, Donald Grobe; Coro y Orquesta Sinfónica de la Radio de Baviera, Director: Rafael Kubelik."},
]

export default discotecaCadis;